import 'package:flutter/material.dart';

class AppLanguage {
  final String code, nativeName, englishName, flag;

  const AppLanguage({
    required this.code,
    required this.nativeName,
    required this.englishName,
    required this.flag,
  });
}

const kLanguages = [
  AppLanguage(
    code: 'en',
    nativeName: 'English',
    englishName: 'English',
    flag: '🇬🇧',
  ),
  AppLanguage(
    code: 'ur',
    nativeName: 'اردو',
    englishName: 'Urdu',
    flag: '🇵🇰',
  ),
  AppLanguage(
    code: 'pa',
    nativeName: 'پنجابی',
    englishName: 'Punjabi',
    flag: '🏔️',
  ),
  AppLanguage(
    code: 'ps',
    nativeName: 'پښتو',
    englishName: 'Pashto',
    flag: '🌿',
  ),
];

class LanguageProvider extends ChangeNotifier {
  static final LanguageProvider instance = LanguageProvider._();
  LanguageProvider._();

  String _code = 'en';
  String get code => _code;
  bool get isRtl => _code == 'ur' || _code == 'ps' || _code == 'pa';

  void set(String code) {
    _code = code;
    notifyListeners();
  }

  static const Map<String, Map<String, String>> _s = {
    'en': {
      'app_name': 'RASTA',
      'tagline': 'REAL-TIME BUS TRACKER',
      'welcome': 'Welcome back 👋',
      'login_sub': 'Login to track your bus',
      'email': 'EMAIL',
      'password': 'PASSWORD',
      'login': 'Login',
      'or': 'or',
      'create_account': 'Create an account',
      'forgot': 'Forgot password?',
      'register_title': 'Create Account',
      'register_sub': 'Join Rasta and track your bus',
      'full_name': 'FULL NAME',
      'have_account': 'have an account?',
      'login_instead': 'Login instead',
      'good_morning': 'Good morning,',
      'search_hint': 'Search route or stop…',
      'live_bus': 'Live Bus',
      'all_routes': 'All Routes',
      'schedule': 'Schedule',
      'nearby': 'Nearby Stops',
      'my_routes': 'My Subscribed Routes',
      'on_time': 'On Time',
      'settings': 'Settings',
      'language': 'Language',
      'notifications': 'Notifications',
      'delay_alerts': 'Delay Alerts',
      'delay_sub': 'Notify on bus delays',
      'arrival_alerts': 'Arrival Alerts',
      'arrival_sub': 'Bus near your stop',
      'help': 'Help & Contact',
      'contact_sub': 'Report issue or feedback',
      'logout': 'Logout',
      'lang_title': 'App Language',
      'lang_sub': 'Select your preferred language',
      'applies_inst': 'Applies instantly — no restart needed',
      'my_subs': 'My Subscriptions',
      'active_routes': '2 active routes',
      'alert_hist': 'Alert History',
      'last_alerts': 'Last 50 alerts',
      'notif_settings': 'Notification Settings',
      'manage_pref': 'Manage preferences',
      'edit_profile': 'Edit Profile',
      'name_email': 'Name, email, password',
      'select_lang': 'Select Language',
      'no_subs_msg':
          'No subscribed routes yet.\nSubscribe to a route to see it here.',
      'all_routes_label': 'All Routes',
    },

    'ur': {
      'app_name': 'راستہ',
      'tagline': 'ریئل ٹائم بس ٹریکر',
      'welcome': 'خوش آمدید 👋',
      'login_sub': 'اپنی بس ٹریک کریں',
      'email': 'ای میل',
      'password': 'پاس ورڈ',
      'login': 'لاگ ان',
      'or': 'یا',
      'create_account': 'اکاؤنٹ بنائیں',
      'forgot': 'پاس ورڈ بھول گئے؟',
      'register_title': 'اکاؤنٹ بنائیں',
      'register_sub': 'راستہ سے جڑیں',
      'full_name': 'پورا نام',
      'have_account': 'پہلے سے اکاؤنٹ ہے؟',
      'login_instead': 'لاگ ان کریں',
      'good_morning': 'صبح بخیر،',
      'search_hint': 'روٹ یا اسٹاپ تلاش کریں…',
      'live_bus': 'لائیو بس',
      'all_routes': 'تمام روٹس',
      'schedule': 'شیڈول',
      'nearby': 'قریبی اسٹاپ',
      'my_routes': 'سبسکرائب روٹس',
      'on_time': 'وقت پر',
      'settings': 'ترتیبات',
      'language': 'زبان',
      'notifications': 'اطلاعات',
      'delay_alerts': 'تاخیر الرٹ',
      'delay_sub': 'بس تاخیر پر اطلاع',
      'arrival_alerts': 'آمد الرٹ',
      'arrival_sub': 'بس آپ کے اسٹاپ کے قریب',
      'help': 'مدد اور رابطہ',
      'contact_sub': 'شکایت یا رائے',
      'logout': 'لاگ آؤٹ',
      'lang_title': 'ایپ زبان',
      'lang_sub': 'اپنی زبان چنیں',
      'applies_inst': 'فوری اطلاق',
      'my_subs': 'میری سبسکرپشن',
      'active_routes': '2 فعال روٹس',
      'alert_hist': 'الرٹ ہسٹری',
      'last_alerts': 'آخری 50 الرٹس',
      'notif_settings': 'اطلاع کی ترتیبات',
      'manage_pref': 'ترجیحات مینیج کریں',
      'edit_profile': 'پروفائل ترمیم',
      'name_email': 'نام، ای میل، پاس ورڈ',
      'select_lang': 'زبان منتخب کریں',
      'no_subs_msg': 'ابھی کوئی سبسکرائب روٹ نہیں۔\nکوئی روٹ سبسکرائب کریں۔',
      'all_routes_label': 'تمام روٹس',
    },

    'pa': {
      'app_name': 'راستہ',
      'tagline': 'ریئل ٹائم بس ٹریکر',
      'welcome': 'جی آیاں نوں 👋',
      'login_sub': 'اپنی بس ٹریک کرو',
      'email': 'ای میل',
      'password': 'پاس ورڈ',
      'login': 'لاگ ان',
      'or': 'یا',
      'create_account': 'اکاؤنٹ بناؤ',
      'forgot': 'پاس ورڈ بھل گئے؟',
      'register_title': 'اکاؤنٹ بناؤ',
      'register_sub': 'راستہ نال جڑو',
      'full_name': 'پورا ناں',
      'have_account': 'پہلاں توں اکاؤنٹ اے؟',
      'login_instead': 'لاگ ان کرو',
      'good_morning': 'صبح بخیر،',
      'search_hint': 'روٹ یا اسٹاپ لبھو…',
      'live_bus': 'لائیو بس',
      'all_routes': 'سارے روٹ',
      'schedule': 'شیڈول',
      'nearby': 'نیڑے اسٹاپ',
      'my_routes': 'میرے سبسکرائب روٹ',
      'on_time': 'ویلے تے',
      'settings': 'ترتیباں',
      'language': 'زبان',
      'notifications': 'اطلاعاں',
      'delay_alerts': 'دیری الرٹ',
      'delay_sub': 'بس دیری تے اطلاع',
      'arrival_alerts': 'آمد الرٹ',
      'arrival_sub': 'بس تیرے اسٹاپ دے نیڑے',
      'help': 'مدد تے رابطہ',
      'contact_sub': 'شکایت یا رائے',
      'logout': 'لاگ آؤٹ',
      'lang_title': 'ایپ زبان',
      'lang_sub': 'اپنی زبان چنو',
      'applies_inst': 'فوری لاگو',
      'my_subs': 'میریاں سبسکرپشناں',
      'active_routes': '2 فعال روٹ',
      'alert_hist': 'الرٹ ہسٹری',
      'last_alerts': 'پچھلے 50 الرٹ',
      'notif_settings': 'اطلاع دیاں ترتیباں',
      'manage_pref': 'ترجیحاں منیج کرو',
      'edit_profile': 'پروفائل بدلو',
      'name_email': 'ناں، ای میل، پاس ورڈ',
      'select_lang': 'زبان چنو',
      'no_subs_msg': 'ہلے کوئی سبسکرائب روٹ نئیں۔\nکوئی روٹ سبسکرائب کرو۔',
      'all_routes_label': 'سارے روٹ',
    },

    'ps': {
      'app_name': 'لار',
      'tagline': 'ریل ټایم بس ټریکر',
      'welcome': 'ښه راغلاست 👋',
      'login_sub': 'خپله بس تعقیب کړئ',
      'email': 'بریښنالیک',
      'password': 'پټنوم',
      'login': 'ننوتل',
      'or': 'یا',
      'create_account': 'حساب جوړ کړئ',
      'forgot': 'پټنوم مو هیر دی؟',
      'register_title': 'حساب جوړ کړئ',
      'register_sub': 'راسته سره یوځای شئ',
      'full_name': 'بشپړ نوم',
      'have_account': 'حساب لرئ؟',
      'login_instead': 'ننوتل',
      'good_morning': 'سهار مو پخیر،',
      'search_hint': 'لاره پلټئ…',
      'live_bus': 'ژوندۍ بس',
      'all_routes': 'ټولې لارې',
      'schedule': 'مهالویش',
      'nearby': 'نږدې توقف',
      'my_routes': 'ګډون شوې لارې',
      'on_time': 'پر وخت',
      'settings': 'امستنې',
      'language': 'ژبه',
      'notifications': 'خبرتیاوې',
      'delay_alerts': 'د ځنډ خبرتیا',
      'delay_sub': 'د بس د ځنډ خبرتیا ترلاسه کړئ',
      'arrival_alerts': 'د رسېدو خبرتیا',
      'arrival_sub': 'بس ستاسو تمځي ته نږدې دی',
      'help': 'مرسته او اړیکه',
      'contact_sub': 'ستونزه یا نظر راپور کړئ',
      'logout': 'وتل',
      'lang_title': 'د اپلیکیشن ژبه',
      'lang_sub': 'خپله خوښه ژبه وټاکئ',
      'applies_inst': 'سمدستي پلي کېږي',
      'my_subs': 'زما ګډونونه',
      'active_routes': '2 فعالې لارې',
      'alert_hist': 'د خبرتیا تاریخچه',
      'last_alerts': 'وروستي 50 خبرتیاوې',
      'notif_settings': 'د خبرتیا امستنې',
      'manage_pref': 'غوره توبونه تنظیم کړئ',
      'edit_profile': 'پروفایل سمول',
      'name_email': 'نوم، برېښنالیک، پټنوم',
      'select_lang': 'ژبه وټاکئ',
      'no_subs_msg': 'لا تر اوسه هیڅ ګډون شوې لاره نشته.\nیوه لاره ګډون کړئ.',
      'all_routes_label': 'ټولې لارې',
    },
  };

  static String tr(String key) {
    return _s[instance._code]?[key] ?? _s['en']![key] ?? key;
  }
}
